Repository DIT112-V21/group-02, pull requests merged in 2021-05, with the labels that each got.

#63 Database implementation
  server/.gitignore
  server/index.js
  server/package-lock.json
  server/package.json
  smartcar_frontend/src/App.js
  smartcar_frontend/src/Components/leaderboard/LeaderBoard.css
  smartcar_frontend/src/components/difficulty/Difficulty.js
  smartcar_frontend/src/components/leaderboard/LeaderBoard.js
  smartcar_frontend/src/components/race/Race.css
  smartcar_frontend/src/components/race/Race.js
  smartcar_frontend/src/pages/home/Home.css
Labels: sprint2

#71 Website UI compatibility
  smartcar_frontend/src/components/camera/Camera.js
  smartcar_frontend/src/components/leaderboard/LeaderBoard.css
  smartcar_frontend/src/components/leaderboard/LeaderBoard.js
  smartcar_frontend/src/components/race/Race.css
  smartcar_frontend/src/components/race/Race.js
Labels: enhancement, sprint3

#80 Login component implementation
  server/index.js
  smartcar_frontend/src/App.js
  smartcar_frontend/src/components/animatedCar/SpringDemo.js
  smartcar_frontend/src/components/race/Race.js
  smartcar_frontend/src/pages/home/Home.css
  smartcar_frontend/src/pages/home/Home.js
  smartcar_frontend/src/pages/login/Login.js
Labels: enhancement, sprint4

#83 Times and login screen css fix
  smartcar_frontend/src/App.js
  smartcar_frontend/src/components/Times.js
  smartcar_frontend/src/components/leaderboard/LeaderBoard.css
  smartcar_frontend/src/components/leaderboard/LeaderBoard.js
  smartcar_frontend/src/components/times/Times.css
  smartcar_frontend/src/components/times/Times.js
  smartcar_frontend/src/pages/login/Login.css
  smartcar_frontend/src/pages/login/Login.js
Labels: sprint4

#85 Racing times completed, Leaderboard updated
  server/index.js
  smartcar_frontend/src/App.js
  smartcar_frontend/src/components/leaderboard/LeaderBoard.css
  smartcar_frontend/src/components/leaderboard/LeaderBoard.js
  smartcar_frontend/src/components/times/Times.css
  smartcar_frontend/src/components/times/Times.js
Labels: enhancement

#98 Keylogger on website
  smartcar_frontend/src/components/race/Race.js
Labels: PRIORITY 3, enhancement, sprint4

#106 Developers guide
  README.md
  godot-resources/mods/RaceAgainstMod/project.godot
  images/citymap.PNG
  images/difficulties.PNG
  images/horrormap.PNG
  images/leaderboard.PNG
  images/menu.PNG
  images/race.PNG
  images/racemap.PNG
  images/times.PNG
Labels: documentation
