Repository DIT112-V21/group-02, pull requests merged in 2021-04, with the labels that each got.

#26 Update obstacle avoidance version 1.0.1
  .github/workflows/arduino-build.yml
  .gitignore
  .vscode/settings.json
  Pipfile
  Pipfile.lock
  arduino/smartcar/secrets-defaults.hpp
  arduino/smartcar/smartcar.ino
  arduino/smartcar/topics.hpp
  src/__init__.py
  src/connection/__init__.py
  src/connection/__pycache__/__init__.cpython-37.pyc
  src/connection/__pycache__/__init__.cpython-39.pyc
  src/connection/__pycache__/publisher.cpython-37.pyc
  src/connection/__pycache__/publisher.cpython-39.pyc
  src/connection/__pycache__/topic.cpython-37.pyc
  src/connection/__pycache__/topic.cpython-39.pyc
  src/connection/connecter.py
  src/connection/topic.py
  src/controls/__init__.py
  src/controls/__pycache__/__init__.cpython-39.pyc
  src/controls/keyboard.py
  src/main.py
Labels: PRIORITY 1, enhancement, sprint1

#30 Remove the gitignore items that made it into repo
  .gitignore
  .vscode/settings.json
  src/connection/__pycache__/__init__.cpython-37.pyc
  src/connection/__pycache__/__init__.cpython-39.pyc
  src/connection/__pycache__/publisher.cpython-37.pyc
  src/connection/__pycache__/publisher.cpython-39.pyc
  src/connection/__pycache__/topic.cpython-37.pyc
  src/connection/__pycache__/topic.cpython-39.pyc
  src/controls/__pycache__/__init__.cpython-39.pyc
Labels: bug

#34 Discord bot
  .gitignore
  Pipfile
  Pipfile.lock
  package-lock.json
  package.json
  python/__init__.py
  python/connection/__init__.py
  python/connection/connecter.py
  python/connection/topic.py
  python/controls/__init__.py
  python/controls/keyboard.py
  python/discord/__init__.py
  python/discord/bot.py
  python/main.py
Labels: enhancement, sprint2

#39 Implement SmarCar and Not get stuck
  arduino/smartcar/smartcar.ino
Labels: PRIORITY 2, enhancement, sprint2

#44 Camera integration
  arduino/smartcar/smartcar.ino
  package-lock.json
  package.json
  python/connection/connecter.py
  python/controls/__init__.py
  python/controls/keyboard.py
  smartcar_frontend/backend/example/Subscriber.js
  smartcar_frontend/package-lock.json
  smartcar_frontend/package.json
  smartcar_frontend/src/App.js
  smartcar_frontend/src/components/Timer.js
  smartcar_frontend/src/components/Times.js
  smartcar_frontend/src/components/camera/Camera.js
  smartcar_frontend/src/components/camera/CanvasReactExample.js
  smartcar_frontend/src/components/difficulty/Difficulty.js
  smartcar_frontend/src/components/leaderboard/LeaderBoard.js
  smartcar_frontend/src/components/race/Controller.js
  smartcar_frontend/src/components/race/Home/Difficulty.js
  smartcar_frontend/src/components/race/Home/DifficultyOption.css
  smartcar_frontend/src/components/race/Home/DifficultyOption.js
  smartcar_frontend/src/components/race/Home/Home.css
  smartcar_frontend/src/components/race/Home/Home.js
  smartcar_frontend/src/components/race/Home/LoadingScreen.js
  smartcar_frontend/src/components/race/Race.css
  smartcar_frontend/src/components/race/Race.js
  smartcar_frontend/src/components/race/Racing/Controller.js
  smartcar_frontend/src/components/race/Racing/Race.css
  smartcar_frontend/src/components/race/Racing/Race.js
  smartcar_frontend/src/index.js
  smartcar_frontend/src/pages/home/Home.css
  smartcar_frontend/src/pages/home/Home.js
  smartcar_frontend/src/pages/loading/LoadingScreen.js
  smartcar_frontend/src/reportWebVitals.js
  smartcar_frontend/src/resources/logo.png
  smartcar_frontend/src/style/App.css
  smartcar_frontend/src/style/index.css
  smartcar_frontend/src/tests/App.test.js
  smartcar_frontend/src/tests/setupTests.js
Labels: enhancement, sprint2

#45 Fix MQTT authenticationdata
  arduino/smartcar/secrets-defaults.hpp
  arduino/smartcar/smartcar.ino
  smartcar_frontend/package-lock.json
Labels: bug

#46 Bug Fix
  arduino/smartcar/smartcar.ino
  smartcar_frontend/src/App.js
  smartcar_frontend/src/components/camera/Camera.js
  smartcar_frontend/src/components/race/Home/Difficulty.js
  smartcar_frontend/src/components/race/Home/DifficultyOption.css
  smartcar_frontend/src/components/race/Home/DifficultyOption.js
  smartcar_frontend/src/components/race/Home/Home.css
  smartcar_frontend/src/components/race/Home/Home.js
  smartcar_frontend/src/components/race/Home/LoadingScreen.js
  smartcar_frontend/src/components/race/Race.js
  smartcar_frontend/src/components/race/Racing/Controller.js
  smartcar_frontend/src/components/race/Racing/Race.css
  smartcar_frontend/src/components/race/Racing/Race.js
  smartcar_frontend/src/pages/home/Home.js
Labels: bug

#48 Joystick interface and basic functionality
  arduino/smartcar/secrets-defaults.hpp
  arduino/smartcar/smartcar.ino
  smartcar_frontend/backend/example/App.js
  smartcar_frontend/package-lock.json
  smartcar_frontend/package.json
  smartcar_frontend/src/App.js
  smartcar_frontend/src/components/Times.js
  smartcar_frontend/src/components/difficulty/Difficulty.js
  smartcar_frontend/src/components/race/Controller.js
  smartcar_frontend/src/components/race/Joystick.js
  smartcar_frontend/src/components/race/Race.css
  smartcar_frontend/src/components/race/Race.js
  smartcar_frontend/src/index.js
  smartcar_frontend/src/pages/home/Home.js
  smartcar_frontend/src/style/App.css
  smartcar_frontend/src/style/index.css
Labels: sprint2

#60 Reactjs
  smartcar_frontend/package-lock.json
  smartcar_frontend/package.json
  smartcar_frontend/src/App.js
  smartcar_frontend/src/Components/animatedCar/SpringDemo.js
  smartcar_frontend/src/Components/leaderboard/LeaderBoard.css
  smartcar_frontend/src/components/Times.js
  smartcar_frontend/src/components/camera/Camera.js
  smartcar_frontend/src/components/difficulty/Difficulty.js
  smartcar_frontend/src/components/leaderboard/LeaderBoard.js
  smartcar_frontend/src/pages/home/Home.css
  smartcar_frontend/src/pages/home/Home.js
  smartcar_frontend/src/pages/loading/LoadingScreen.js
  smartcar_frontend/src/pages/login/Login.css
  smartcar_frontend/src/pages/login/Login.js
  smartcar_frontend/src/resources/car.svg
  smartcar_frontend/src/resources/cloud.svg
  smartcar_frontend/src/style/index.css
Labels: sprint2
